[workspace]
members = [
  "arcon",
  "arcon/proto_tests"
]

# TODO fix these later again
exclude = [
	"arcon_codegen",
    "arcon/experiments",
  	"arcon_compiler"
]

[profile.dev.package.grpcio-sys]
opt-level = 1 # weird issue with _FORTIFY_SOURCE makes the compilation fail on some systes
