[package]
name = "spec"
version = "0.1.0"
authors = ["Max Meldrum <max@meldrum.se>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
tempfile = "3"
