[package]
name = "arcon_build"
version = "0.2.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
readme = "README.md"
license = "AGPL-3.0-only"
description = """
Protobuf builder for arcon
"""

[features]
arcon_serde = []
unsafe_flight = []

[dependencies]
prost-build = "0.6"
