[package]
name = "arcon_allocator"
version = "0.2.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
readme = "README.md"
license = "AGPL-3.0-only"
description = """
allocator for the arcon runtime
"""

[dependencies]
fxhash = "0.2.1"
