[package]
name = "arcon_state_derive"
version = "0.2.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"
license = "AGPL-3.0-only"
description = """
Arcon State Derive Macro
"""

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
