name: arcon
on: 
  pull_request:
    branches: [state_index_experiment]
  push:
    branches: [state_index_experiment]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
            default: true
            profile: minimal
            components: rustfmt
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
